apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-internal
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-internal
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BlindGarret/cloudden.git
    path: ./core/charts/internal-ingress
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-internal
  syncPolicy:
    automated:
      selfHeal: true
      prune: true