apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-catalog
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BlindGarret/cloudden.git
    path: ./service-catalog/chart
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true